# permissions for end users to view appservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: appservice-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kop
    app.kubernetes.io/part-of: kop
    app.kubernetes.io/managed-by: kustomize
  name: appservice-viewer-role
rules:
- apiGroups:
  - webapp.alainrk.com
  resources:
  - appservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.alainrk.com
  resources:
  - appservices/status
  verbs:
  - get
